#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ironic-lib
Version  : 3.0.0
Release  : 18
URL      : https://files.pythonhosted.org/packages/c2/4c/6e5ecb8de23fe7bb4476b98fcf7c711d221317cf196706c07f61c4aa0e1a/ironic-lib-3.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c2/4c/6e5ecb8de23fe7bb4476b98fcf7c711d221317cf196706c07f61c4aa0e1a/ironic-lib-3.0.0.tar.gz
Summary  : Ironic common library
Group    : Development/Tools
License  : Apache-2.0
Requires: ironic-lib-license = %{version}-%{release}
Requires: ironic-lib-python = %{version}-%{release}
Requires: ironic-lib-python3 = %{version}-%{release}
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.serialization
Requires: oslo.service
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: zeroconf
BuildRequires : buildreq-distutils3
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.serialization
BuildRequires : oslo.service
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : requests
BuildRequires : zeroconf

%description
ironic-lib
        ==========
        
        Team and repository tags
        ------------------------

%package license
Summary: license components for the ironic-lib package.
Group: Default

%description license
license components for the ironic-lib package.


%package python
Summary: python components for the ironic-lib package.
Group: Default
Requires: ironic-lib-python3 = %{version}-%{release}

%description python
python components for the ironic-lib package.


%package python3
Summary: python3 components for the ironic-lib package.
Group: Default
Requires: python3-core
Provides: pypi(ironic_lib)
Requires: pypi(oslo.concurrency)
Requires: pypi(oslo.config)
Requires: pypi(oslo.i18n)
Requires: pypi(oslo.log)
Requires: pypi(oslo.serialization)
Requires: pypi(oslo.service)
Requires: pypi(oslo.utils)
Requires: pypi(pbr)
Requires: pypi(requests)
Requires: pypi(zeroconf)

%description python3
python3 components for the ironic-lib package.


%prep
%setup -q -n ironic-lib-3.0.0
cd %{_builddir}/ironic-lib-3.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583703296
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ironic-lib
cp %{_builddir}/ironic-lib-3.0.0/LICENSE %{buildroot}/usr/share/package-licenses/ironic-lib/c700a8b9312d24bdc57570f7d6a131cf63d89016
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ironic-lib/c700a8b9312d24bdc57570f7d6a131cf63d89016

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
