#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ironic-lib
Version  : 2.16.1
Release  : 5
URL      : https://files.pythonhosted.org/packages/f5/f9/36cc75243fdde01c45d749a389b7e2a5d7335a2651b4a86dcb3e56a65026/ironic-lib-2.16.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/f5/f9/36cc75243fdde01c45d749a389b7e2a5d7335a2651b4a86dcb3e56a65026/ironic-lib-2.16.1.tar.gz
Summary  : Ironic common library
Group    : Development/Tools
License  : Apache-2.0
Requires: ironic-lib-license = %{version}-%{release}
Requires: ironic-lib-python = %{version}-%{release}
Requires: ironic-lib-python3 = %{version}-%{release}
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.serialization
Requires: oslo.service
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : oslo.log
BuildRequires : oslo.service
BuildRequires : pbr

%description
==========
ironic-lib
==========
Team and repository tags
------------------------

%package license
Summary: license components for the ironic-lib package.
Group: Default

%description license
license components for the ironic-lib package.


%package python
Summary: python components for the ironic-lib package.
Group: Default
Requires: ironic-lib-python3 = %{version}-%{release}

%description python
python components for the ironic-lib package.


%package python3
Summary: python3 components for the ironic-lib package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ironic-lib package.


%prep
%setup -q -n ironic-lib-2.16.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547172968
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ironic-lib
cp LICENSE %{buildroot}/usr/share/package-licenses/ironic-lib/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ironic-lib/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
